#!/usr/bin/with-contenv bash

if [ "${RT_TOKEN}" != "" ] && [ "${RT_MASTERS}" != "" ];then
  if [ -n "${RT_COMPLETED}" ];then
    su abc -c "/usr/bin/rtelegram -token=${RT_TOKEN} -masters=${RT_MASTERS} -url=/run/php/.rtorrent.sock -logfile=/config/log/rtelegram/rtelegram.log -completed-torrents-logfile=${RT_COMPLETED}"
  else
    su abc -c "/usr/bin/rtelegram -token=${RT_TOKEN} -masters=${RT_MASTERS} -url=/run/php/.rtorrent.sock -logfile=/config/log/rtelegram/rtelegram.log"
  fi
fi
