version: '3'
services:
    rutorrent:
      build:
        dockerfile: Dockerfile
        context: .
        args:
          - MAXMIND_LICENSE_KEY=$MAXMIND_LICENSE_KEY
          - MAXMIND_USER=$MAXMIND_USER
          - MAXMIND_PASSWORD=$MAXMIND_PASSWORD
          - RTORRENT_VER=0.9.8
          - LIBTORRENT_VER=0.13.8
      container_name: rutorrent-flood
      networks:
        - default
      tty: true
      volumes:
        - ./rutorrent-conf:/config
        - ./rutorrent-downloads:/downloads
      environment:
        - PUID=0
        - PGID=0
        - TZ=Europe/Kiev
        - CREATE_SUBDIR_BY_TRACKERS=NO
        - SSL_ENABLED=YES
        - RT_TOKEN=
        - RT_MASTERS=
        - RT_COMPLETED=/config/log/rtorrent/rtorrent_completed.log
      ports:
        - "8880:80"
        - "32316:52316"
        - "3333:3000"
