#!/usr/bin/with-contenv bash

cd /usr/flood || exit

FLOOD_START_PARAMS="--host 0.0.0.0 --port 3000 --rundir /config/flood "
if [ "$SSL_ENABLED" == "yes" ]
then
  FLOOD_START_PARAMS=$FLOOD_START_PARAMS"--ssl true --sslkey /config/nginx/key.pem --sslcert /config/nginx/cert.pem"
fi

exec s6-setuidgid abc npm run start -- $FLOOD_START_PARAMS
